### ISSUE TITLE
Add scala 2.12 build on Maven Central

### ISSUE THREAD

**Issue by howard-branch** [smootoo/TableDiff#5]

**Comment by smootoo** [comment]
Hi Howard!
I'll try to get it up when I get home tonight.

**Comment by smootoo** [comment]
New version published http://search.maven.org/#artifactdetails%7Corg.suecarter%7Ctablediff_2.12%7C1.0.2%7Cjar

**Comment by howard-branch** [comment]
thanks very much Sue!
